spring.application.name=ecommerce

# Base de datos local. En otros ambientes se puede configurar mediante variables de entorno.
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&serverTimezone=America/Santiago}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring